### ISSUE TITLE
Using cat /etc/lsb-release instead of lsb_release -d

### ISSUE THREAD

**Issue by ranginui** [jjaone/KohaLXC#2]
Would a patch changing the playbook to use lsb_release -d instead of cat /etc/lsb-release be accepted? (/etc/lsb-release doesn't exist on Debian)

**Comment by jjaone** [comment]
Sure, thanks for reporting, there probably are other Ubuntu-specific shell commands in the playbook and scripts, cause we are on Ubuntu 14.04/16.04 Server LTS in LXC/host envs.

**Comment by jjaone** [comment]
Closing, fixed in commit: https://github.com/jjaone/KohaLXC/commit/4b807aed979fa90cf246f7f040dab4049aab0ccd
